[build]
  command = "cd exampleSite && hugo --gc --minify -D -b $URL"
  publish = "exampleSite/public"

[build.environment]
HUGO_VERSION = "0.119.0"
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"
TZ = "Australia/Melbourne"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"
